"""empty message

Revision ID: 292e1012607d
Revises: 00ba576e78ba
Create Date: 2020-08-27 09:55:24.127263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e1012607d'
down_revision = '00ba576e78ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
