"""empty message

Revision ID: 68d4ab028552
Revises: a2629130c83e
Create Date: 2020-11-18 21:44:54.642510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d4ab028552'
down_revision = 'a2629130c83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_userpolls', sa.Column('option_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_userpolls', 'option_id')
    # ### end Alembic commands ###
