""" host_id

Revision ID: 6e3e817bb7dd
Revises: 6f775724b2a6
Create Date: 2020-08-01 15:43:31.765582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3e817bb7dd'
down_revision = '6f775724b2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('likes', schema=None) as batch_op:
    #    batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('thumb_up')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_up', sa.INTEGER(), nullable=True))

   # with op.batch_alter_table('likes', schema=None) as batch_op:
   #     batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
