"""empty message

Revision ID: 7111c902b158
Revises: dc5cc1a6c2b4
Create Date: 2020-07-18 11:31:00.569679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7111c902b158'
down_revision = 'dc5cc1a6c2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('comment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'comment')
    # ### end Alembic commands ###
