"""empty message

Revision ID: 79bb2830a1a3
Revises: 8dd8df1e2325
Create Date: 2020-09-29 17:22:56.124742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bb2830a1a3'
down_revision = '8dd8df1e2325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sqlite_sequence')
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('message_body', sa.String(length=512), nullable=True))
        batch_op.drop_column('from_username')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(length=256), nullable=True))
        batch_op.add_column(sa.Column('from_username', sa.TEXT(length=128), nullable=True))
        batch_op.drop_column('message_body')
        batch_op.drop_column('from_user')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
