"""empty message

Revision ID: 86115054b225
Revises: 1392237c7d0d
Create Date: 2020-07-29 11:15:36.570639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86115054b225'
down_revision = '1392237c7d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'user_id')
    op.drop_column('likes', 'post_id')
    # ### end Alembic commands ###
