"""empty message

Revision ID: 881dc29b5879
Revises: 5259ca8564bf
Create Date: 2020-07-30 16:38:33.939166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881dc29b5879'
down_revision = '5259ca8564bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'likes', type_='foreignkey')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
