"""empty message

Revision ID: 8dd8df1e2325
Revises: c897e45f6bb0
Create Date: 2020-09-29 15:05:33.138484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd8df1e2325'
down_revision = 'c897e45f6bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_username', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wx_access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_access_token',
    sa.Column('access_token', sa.VARCHAR(length=512), nullable=False),
    sa.Column('open_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('expires_in', sa.INTEGER(), nullable=True),
    sa.Column('refresh_token', sa.DATETIME(), nullable=True),
    sa.Column('scope', sa.VARCHAR(length=32), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.drop_table('wechat_message')
    # ### end Alembic commands ###
