"""empty message

Revision ID: 995af880be3a
Revises: 3605cddaa6aa
Create Date: 2020-08-01 17:01:59.751346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995af880be3a'
down_revision = '3605cddaa6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
