"""empty message

Revision ID: a2629130c83e
Revises: 0dcab24ebace
Create Date: 2020-11-16 20:47:54.281129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2629130c83e'
down_revision = '0dcab24ebace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poll_options_ibfk_1', 'poll_options', type_='foreignkey')
    op.drop_column('poll_options', 'topic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_options', sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('poll_options_ibfk_1', 'poll_options', 'poll_topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
