"""empty message

Revision ID: a7d7a5bf8ac2
Revises: 993e3f0c94a0
Create Date: 2020-08-21 15:26:58.950290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d7a5bf8ac2'
down_revision = '993e3f0c94a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('fs_start', sa.DateTime(), nullable=True),
    sa.Column('fs_end', sa.DateTime(), nullable=True),
    sa.Column('qa_start', sa.DateTime(), nullable=True),
    sa.Column('qa_end', sa.DateTime(), nullable=True),
    sa.Column('uat_start', sa.DateTime(), nullable=True),
    sa.Column('uat_end', sa.DateTime(), nullable=True),
    sa.Column('sign_off', sa.DateTime(), nullable=True),
    sa.Column('target_release', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=True),
    sa.Column('current_comment', sa.String(length=256), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
