"""empty message

Revision ID: c897e45f6bb0
Revises: 292e1012607d
Create Date: 2020-09-26 16:19:34.705997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c897e45f6bb0'
down_revision = '292e1012607d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_access_token',
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('open_id', sa.String(length=64), nullable=True),
    sa.Column('expires_in', sa.INTEGER(), nullable=True),
    sa.Column('refresh_token', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('access_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wx_access_token')
    # ### end Alembic commands ###
