"""empty message

Revision ID: e76e06ba8fa7
Revises: c666187e43b2
Create Date: 2020-08-01 15:58:53.705911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e06ba8fa7'
down_revision = 'c666187e43b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
