"""empty message

Revision ID: fa93a9f58dc0
Revises: 
Create Date: 2020-07-06 20:08:41.919169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa93a9f58dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('course', 'startDate')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('startDate', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
